[project]
name = "firn-data-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.10.4",
    "dbt-snowflake>=1.10.0",
    "snowflake-cli>=3.9.1",
]
